import { ButtonStyle } from '@/types/button';

export const defaultButtonStyles: ButtonStyle[] = [
  {
    id: 'glow-pill',
    name: 'Neon Glow',
    description: 'Futuristic pill shape with neon glow effect',
    gradientFrom: '#FF6B35',
    gradientTo: '#F7931E',
    textColor: '#FFFFFF',
    borderRadius: '50px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 0 30px rgba(255, 107, 53, 0.6), 0 8px 25px rgba(255, 107, 53, 0.3)',
    hoverEffect: 'hover:shadow-[0_0_40px_rgba(255,107,53,0.8)] hover:scale-105'
  },
  {
    id: 'angular-modern',
    name: 'Angular Tech',
    description: 'Sharp, modern design with angular edges',
    gradientFrom: '#3B82F6',
    gradientTo: '#1D4ED8',
    textColor: '#FFFFFF',
    borderRadius: '4px',
    padding: '14px 28px',
    fontSize: '15px',
    fontWeight: '800',
    shadow: '0 8px 20px rgba(59, 130, 246, 0.4), inset 0 1px 0 rgba(255,255,255,0.1)',
    hoverEffect: 'hover:translate-y-[-2px] hover:shadow-[0_12px_30px_rgba(59,130,246,0.5)]'
  },
  {
    id: 'soft-organic',
    name: 'Soft Organic',
    description: 'Gentle, organic shape with subtle shadows',
    gradientFrom: '#8B5CF6',
    gradientTo: '#EC4899',
    textColor: '#FFFFFF',
    borderRadius: '24px 8px 24px 8px',
    padding: '18px 36px',
    fontSize: '15px',
    fontWeight: '600',
    shadow: '0 6px 20px rgba(139, 92, 246, 0.25), 0 2px 8px rgba(139, 92, 246, 0.1)',
    hoverEffect: 'hover:scale-110 hover:rotate-1'
  },
  {
    id: 'outlined-minimal',
    name: 'Ghost Outline',
    description: 'Minimalist outlined design with gradient border',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
    textColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '14px 28px',
    fontSize: '14px',
    fontWeight: '600',
    shadow: 'inset 0 0 0 2px rgba(16, 185, 129, 0.3)',
    hoverEffect: 'hover:bg-gradient-to-r hover:from-green-500 hover:to-emerald-600 hover:text-white'
  },
  {
    id: 'elevated-3d',
    name: '3D Elevated',
    description: 'Three-dimensional elevated button with depth',
    gradientFrom: '#EF4444',
    gradientTo: '#DC2626',
    textColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 8px 0 #000000, 0 12px 25px rgba(0,0,0,0.4)',
    hoverEffect: 'hover:translate-y-1'
  },
  {
    id: 'glassmorphism',
    name: 'Glass Effect',
    description: 'Trendy glassmorphism with blur and transparency',
    gradientFrom: '#6B7280',
    gradientTo: '#374151',
    textColor: '#FFFFFF',
    borderRadius: '20px',
    padding: '16px 32px',
    fontSize: '15px',
    fontWeight: '600',
    shadow: '0 8px 32px rgba(31, 38, 135, 0.37), inset 0 1px 0 rgba(255,255,255,0.1)',
    hoverEffect: 'hover:backdrop-blur-lg hover:bg-white/20'
  },
  {
    id: 'retro-vintage',
    name: 'Retro Vintage',
    description: 'Nostalgic 80s style with bold typography',
    gradientFrom: '#F59E0B',
    gradientTo: '#F97316',
    textColor: '#FFFFFF',
    borderRadius: '0px',
    padding: '20px 40px',
    fontSize: '18px',
    fontWeight: '900',
    shadow: '8px 8px 0 #000000',
    hoverEffect: 'hover:translate-x-1 hover:translate-y-1'
  },
  {
    id: 'neumorphism',
    name: 'Neumorphic',
    description: 'Soft neumorphic design that appears extruded',
    gradientFrom: '#14B8A6',
    gradientTo: '#0891B2',
    textColor: '#FFFFFF',
    borderRadius: '28px',
    padding: '18px 36px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: '12px 12px 24px rgba(20, 184, 166, 0.2), -12px -12px 24px rgba(255, 255, 255, 0.05)',
    hoverEffect: 'hover:shadow-[6px_6px_12px_rgba(20,184,166,0.3),-6px_-6px_12px_rgba(255,255,255,0.1)]'
  },
  {
    id: 'icon-heavy',
    name: 'Icon Focus',
    description: 'Large icon with compact text layout',
    gradientFrom: '#8B5CF6',
    gradientTo: '#6366F1',
    textColor: '#FFFFFF',
    borderRadius: '16px',
    padding: '12px 20px',
    fontSize: '13px',
    fontWeight: '600',
    shadow: '0 4px 15px rgba(139, 92, 246, 0.3)',
    hoverEffect: 'hover:scale-105 hover:rotate-3'
  },
  {
    id: 'minimal-flat',
    name: 'Ultra Minimal',
    description: 'Clean, flat design with subtle interactions',
    gradientFrom: '#6B7280',
    gradientTo: '#4B5563',
    textColor: '#FFFFFF',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '14px',
    fontWeight: '500',
    shadow: 'none',
    hoverEffect: 'hover:bg-opacity-80 hover:translate-y-[-1px]'
  },
  {
    id: 'pixel-art',
    name: 'Pixel Art',
    description: 'Retro 8-bit gaming inspired design',
    gradientFrom: '#4ade80',
    gradientTo: '#16a34a',
    textColor: '#FFFFFF',
    borderRadius: '0px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '4px 4px 0px #000000',
    hoverEffect: 'hover:translate-x-1 hover:translate-y-1 hover:shadow-none'
  },
  {
    id: 'subtle-shimmer',
    name: 'Subtle Shimmer',
    description: 'A modern, elegant button with a soft shimmer effect',
    gradientFrom: '#c084fc',
    gradientTo: '#7e22ce',
    textColor: '#FFFFFF',
    borderRadius: '12px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: '0 10px 20px #00000033',
    hoverEffect: 'animate-shimmer'
  },
  {
    id: 'skewed-dynamic',
    name: 'Skewed & Dynamic',
    description: 'An energetic button with a skewed transform',
    gradientFrom: '#f87171',
    gradientTo: '#b91c1c',
    textColor: '#FFFFFF',
    borderRadius: '8px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 10px 20px #00000033',
    hoverEffect: 'hover:scale-110'
  },
  {
    id: 'minimalist-icon',
    name: 'Minimalist Icon',
    description: 'A small, icon-focused button for tight spaces',
    gradientFrom: '#60a5fa',
    gradientTo: '#2563eb',
    textColor: '#FFFFFF',
    borderRadius: '50%',
    padding: '16px',
    fontSize: '0px',
    fontWeight: '600',
    shadow: '0 4px 10px #0000004d',
    hoverEffect: 'hover:scale-110'
  },
  {
    id: 'bold-block',
    name: 'Bold Block',
    description: 'A large, impactful button with a thick border',
    gradientFrom: '#fbbf24',
    gradientTo: '#f59e0b',
    textColor: '#FFFFFF',
    borderRadius: '4px',
    padding: '24px 48px',
    fontSize: '20px',
    fontWeight: '800',
    shadow: '0 0 0 4px #000000',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    description: 'A fun, comic book-style button with a halftone pattern',
    gradientFrom: '#facc15',
    gradientTo: '#eab308',
    textColor: '#000000',
    borderRadius: '12px',
    padding: '20px 40px',
    fontSize: '18px',
    fontWeight: '900',
    shadow: '6px 6px 0px #000000',
    hoverEffect: 'hover:translate-x-1 hover:translate-y-1'
  },
  {
    id: 'caution-tape',
    name: 'Caution Tape',
    description: 'A rugged, industrial-style button that demands attention',
    gradientFrom: '#fde047',
    gradientTo: '#facc15',
    textColor: '#000000',
    borderRadius: '0px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '800',
    shadow: '0 0 0 4px #000000',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'cyberpunk-glitch',
    name: 'Cyberpunk Glitch',
    description: 'A futuristic, glitchy button for a high-tech feel',
    gradientFrom: '#00f2ff',
    gradientTo: '#ff00c1',
    textColor: '#ffffff',
    borderRadius: '4px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 0 15px #ff00c1',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'hand-drawn',
    name: 'Hand-Drawn',
    description: 'A sketchy, hand-drawn button for a personal touch',
    gradientFrom: '#ffffff',
    gradientTo: '#e5e5e5',
    textColor: '#000000',
    borderRadius: '16px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: 'none',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'ugly-90s',
    name: 'Ugly 90s',
    description: 'An intentionally clunky, 90s-inspired button',
    gradientFrom: '#00ff00',
    gradientTo: '#0000ff',
    textColor: '#ffff00',
    borderRadius: '0px',
    padding: '20px 40px',
    fontSize: '20px',
    fontWeight: '900',
    shadow: '4px 4px 0px #ff00ff',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'baroque-luxury',
    name: 'Baroque Luxury',
    description: 'An ornate, luxurious button with a touch of gold',
    gradientFrom: '#d4af37',
    gradientTo: '#b8860b',
    textColor: '#ffffff',
    borderRadius: '24px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 0 15px #b8860b',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'wood-grain',
    name: 'Wood Grain',
    description: 'A rustic button with a realistic wood grain texture',
    gradientFrom: '#8B4513',
    gradientTo: '#A0522D',
    textColor: '#ffffff',
    borderRadius: '8px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '2px 2px 5px rgba(0,0,0,0.5)',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'liquid-metal',
    name: 'Liquid Metal',
    description: 'A sleek, futuristic button with a liquid metal sheen',
    gradientFrom: '#d1d5db',
    gradientTo: '#9ca3af',
    textColor: '#1f2937',
    borderRadius: '50px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 0 15px #9ca3af',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'A technical, blueprint-style button for a schematic look',
    gradientFrom: '#3b82f6',
    gradientTo: '#2563eb',
    textColor: '#ffffff',
    borderRadius: '0px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: 'none',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'rusted-metal',
    name: 'Rusted Metal',
    description: 'A grungy, weathered button with a rusted metal texture',
    gradientFrom: '#b91c1c',
    gradientTo: '#7f1d1d',
    textColor: '#ffffff',
    borderRadius: '4px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '2px 2px 5px rgba(0,0,0,0.5)',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'satin-finish',
    name: 'Satin Finish',
    description: 'A smooth, elegant button with a satin-like sheen',
    gradientFrom: '#e5e7eb',
    gradientTo: '#d1d5db',
    textColor: '#1f2937',
    borderRadius: '12px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: '0 10px 20px rgba(0,0,0,0.1)',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'letterpress',
    name: 'Letterpress',
    description: 'A classic, tactile style with inset text',
    gradientFrom: '#f3f4f6',
    gradientTo: '#e5e7eb',
    textColor: '#4b5563',
    borderRadius: '8px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: 'inset 0 2px 4px rgba(0,0,0,0.1)',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'dual-tone',
    name: 'Dual Tone',
    description: 'A modern, split-color design for a bold statement',
    gradientFrom: '#3b82f6',
    gradientTo: '#ef4444',
    textColor: '#ffffff',
    borderRadius: '50px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 10px 20px rgba(0,0,0,0.1)',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'A beautiful button inspired by the northern lights',
    gradientFrom: '#8b5cf6',
    gradientTo: '#ec4899',
    textColor: '#ffffff',
    borderRadius: '16px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '700',
    shadow: '0 0 20px #ec4899',
    hoverEffect: 'hover:scale-105'
  },
  {
    id: 'minimalist-stroke',
    name: 'Minimalist Stroke',
    description: 'A clean, minimalist button with a fine, animated stroke',
    gradientFrom: '#ffffff',
    gradientTo: '#ffffff',
    textColor: '#1f2937',
    borderRadius: '8px',
    padding: '16px 32px',
    fontSize: '16px',
    fontWeight: '600',
    shadow: 'none',
    hoverEffect: 'hover:scale-105'
  }
];

export const colorOptions = [
  { name: 'Orange', value: '#FF6B35' },
  { name: 'Blue', value: '#3B82F6' },
  { name: 'Purple', value: '#8B5CF6' },
  { name: 'Green', value: '#10B981' },
  { name: 'Red', value: '#EF4444' },
  { name: 'Yellow', value: '#F59E0B' },
  { name: 'Pink', value: '#EC4899' },
  { name: 'Teal', value: '#14B8A6' },
  { name: 'Indigo', value: '#6366F1' },
  { name: 'Gray', value: '#6B7280' },
  { name: 'Lime', value: '#84CC16' },
  { name: 'Cyan', value: '#06B6D4' }
];
